#!/bin/sh
set -eu

# Create configuration file from collected templates.
envsubst < /etc/lldap/config.toml.template > /etc/lldap/config.toml

# Crrect permissions for data files.
chown -R /var/lib/lldap

# Run entrypoint under specific user.
cd /usr/share/lldap
exec gosu lldap /usr/bin/lldap run --config-file /etc/lldap/config.toml "$@"
