#!/bin/sh

# Create base directories.
install -D --mode 0755 /run/rspamd
chown -R rspamd:rspamd /run/rspamd /var/lib/rspamd

# Run rspamd in the foreground.
exec /usr/bin/rspamd --no-fork --user rspamd --group rspamd
