[[servers]]
host = "${GRAFANA_AUTH_LDAP_HOST}"
port = ${GRAFANA_AUTH_LDAP_PORT}
use_ssl = false
start_tls = false
ssl_skip_verify = false

bind_dn = "uid=${GRAFANA_AUTH_LDAP_BIND_UID},ou=people,dc=ldap,dc=local"
bind_password = "${GRAFANA_AUTH_LDAP_BIND_PASSWORD}"

search_filter = "(|(uid=%s)(mail=%s))"
search_base_dns = ["dc=ldap,dc=local"]

[servers.attributes]
member_of = "memberOf"
email = "mail"
name = "givenName"
surname = "sn"
username = "uid"

[[servers.group_mappings]]
group_dn = "cn=grafana_admin,ou=groups,dc=ldap,dc=local"
org_role = "Admin"
grafana_admin = true

[[servers.group_mappings]]
group_dn = "cn=grafana_user,ou=groups,dc=ldap,dc=local"
org_role = "Editor"
