FROM docker.io/debian:bookworm-slim@sha256:5f7d5664eae4a192c2d2d6cb67fc3f3c7891a8722cd2903cc35aa649a12b0c8d AS builder
ARG VERSION=1.67.0 # renovate: datasource=github-releases depName=rclone/rclone extractVersion=^v(?<version>.*)$
WORKDIR /src

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    unzip

ADD https://github.com/rclone/rclone/releases/download/v${VERSION}/rclone-v${VERSION}-linux-amd64.zip /src.zip
RUN unzip -j /src.zip && install -D --mode 0755 /src/rclone /build/usr/bin/rclone

FROM docker.io/debian:bookworm-slim@sha256:5f7d5664eae4a192c2d2d6cb67fc3f3c7891a8722cd2903cc35aa649a12b0c8d
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    curl python3 python3-ldap3

RUN adduser --system --group --uid 10000 --no-create-home rclone && \
    install -D --owner rclone --group rclone -d /var/lib/rclone-storage

COPY --from=builder /build /
COPY container/ldap-auth-proxy /usr/bin

USER rclone
ENTRYPOINT ["/usr/bin/rclone"]
