FROM docker.io/debian:bookworm-slim@sha256:0f5f2ad0f82ed101b4ea0e841bb19375fcd0892c2971c0902d790f97f2763502 AS builder
ARG VERSION=1.65.2 # renovate: datasource=github-releases depName=rclone/rclone extractVersion=^v(?<version>.*)$
WORKDIR /src

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    unzip

ADD https://github.com/rclone/rclone/releases/download/v${VERSION}/rclone-v${VERSION}-linux-amd64.zip /src.zip
RUN unzip -j /src.zip && install -D --mode 0755 /src/rclone /build/usr/bin/rclone

FROM docker.io/debian:bookworm-slim@sha256:0f5f2ad0f82ed101b4ea0e841bb19375fcd0892c2971c0902d790f97f2763502
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    curl python3 python3-ldap3

RUN adduser --system --group --uid 10000 --no-create-home rclone && \
    install -D --owner rclone --group rclone -d /var/lib/rclone-storage

COPY --from=builder /build /
COPY container/ldap-auth-proxy /usr/bin

USER rclone
ENTRYPOINT ["/usr/bin/rclone"]
