FROM docker.io/debian:bookworm-slim@sha256:8f8e63bb364a33694362f38ee9a9e38b09eb9eb138584693800b87ca173bfd4a AS builder
ARG VERSION=1.70.3 # renovate: datasource=github-releases depName=rclone/rclone extractVersion=^v(?<version>.*)$
WORKDIR /src

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    unzip

ADD https://github.com/rclone/rclone/releases/download/v${VERSION}/rclone-v${VERSION}-linux-amd64.zip /src.zip
RUN unzip -j /src.zip && install -D --mode 0755 /src/rclone /build/usr/bin/rclone

FROM docker.io/debian:bookworm-slim@sha256:8f8e63bb364a33694362f38ee9a9e38b09eb9eb138584693800b87ca173bfd4a
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    curl python3 python3-ldap3

RUN adduser --system --group --uid 10000 --no-create-home rclone && \
    install -D --owner rclone --group rclone -d /var/lib/rclone-storage

COPY --from=builder /build /
COPY container/ldap-auth-proxy /usr/bin

USER rclone
ENTRYPOINT ["/usr/bin/rclone"]
