{
 "title": "Dovecot",
 "description": "Monitoring for Dovecot, the IMAP server.",
 "tags": [
  "mail",
  "service",
  "public"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Running?",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{instance=\"dovecot:9900\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dovecot_client_connection_total[2m]))"
    }
   ]
  },
  {
   "title": "Outgoing connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dovecot_server_connection_total[2m]))"
    }
   ]
  },
  {
   "title": "Current Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dovecot_build_info", "legendFormat": "{{version}}" }
   ]
  },
  { "title": "Network & Authentication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Authentication Requests",
   "type": "timeseries",
   "description": "The rate of requests for authentication, by `passdb` name and result.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(dovecot_auth_passdb_request_count{}[2m])",
     "legendFormat": "{{passdb_name}}: {{result}}"
    }
   ]
  },
  {
   "title": "User Requests",
   "type": "timeseries",
   "description": "The rate of requests for user information, by `userdb` name and result.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(dovecot_auth_userdb_request_count{}[2m])",
     "legendFormat": "{{userdb_name}}: {{result}}"
    }
   ]
  },
  {
   "title": "Incoming connections",
   "type": "timeseries",
   "description": "The current rate of incoming client connections established.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(dovecot_client_connection_total[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing connections",
   "type": "timeseries",
   "description": "The current rate of outgoing server connections established.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(dovecot_server_connection_total[2m]))"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "IMAP Commands",
   "type": "timeseries",
   "description": "The rate of IMAP commands executed for a authenticated users.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(dovecot_imap_command_total{cmd_name!=\"\",tagged_reply_state!=\"\"}[2m])) by (cmd_name, tagged_reply_state, user)",
     "legendFormat": "{{user}} - {{cmd_name}}: {{tagged_reply_state}}"
    }
   ]
  },
  {
   "title": "SQL Queries",
   "type": "timeseries",
   "description": "The rate of SQL queries executed for a authenticated users.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(dovecot_sql_query_total[2m])) by (query_first_word, error_code)",
     "legendFormat": "{{query_first_word}} {{error_code}}"
    }
   ]
  },
  {
   "title": "Sieve Script Executions",
   "type": "timeseries",
   "description": "The rate of Sieve scripts executing, by script name.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(dovecot_sieve_script_total[2m])) by (script_name, error)",
     "legendFormat": "{{script_name}} {{error}}"
    }
   ]
  },
  {
   "title": "Sieve Script Actions",
   "type": "timeseries",
   "description": "The rate of Sieve script actions taken, by name.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(dovecot_sieve_action_total[2m])) by (action_name)",
     "legendFormat": "{{action_name}}"
    }
   ]
  }
 ]
}