FROM docker.io/debian:bookworm-slim@sha256:8f8e63bb364a33694362f38ee9a9e38b09eb9eb138584693800b87ca173bfd4a AS builder
ARG VERSION=0.19.0 # renovate: datasource=github-releases depName=superseriousbusiness/gotosocial extractVersion=^v(?<version>.*)$
WORKDIR /src

ADD https://github.com/superseriousbusiness/gotosocial/releases/download/v${VERSION}/gotosocial_${VERSION}_linux_amd64.tar.gz /src.tar.gz
RUN tar --no-same-owner -xvzf /src.tar.gz && \
    install -D --mode 0755 /src/gotosocial /build/usr/bin/gotosocial && \
    mkdir -p /build/usr/share/gotosocial && cp -R /src/web /build/usr/share/gotosocial/web

FROM docker.io/debian:bookworm-slim@sha256:8f8e63bb364a33694362f38ee9a9e38b09eb9eb138584693800b87ca173bfd4a
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends curl
RUN adduser --system --group --uid 10000 --home /var/lib/gotosocial gotosocial

COPY --from=builder /build /
COPY container/config /etc/gotosocial
COPY container/run-gotosocial /run-gotosocial

EXPOSE 8080
ENTRYPOINT ["/run-gotosocial"]
