FROM docker.io/debian:bookworm-slim@sha256:88200866dfff7ea7f5cbcb6ec7c8a701889efe6fe859fe64d6990e4b07ea4171 AS builder
ARG VERSION=0.22.1 # renovate: datasource=forgejo-releases depName=superseriousbusiness/gotosocial registryUrl=https://codeberg.org extractVersion=^v(?<version>.*)$
WORKDIR /src

ADD https://codeberg.org/superseriousbusiness/gotosocial/releases/download/v${VERSION}/gotosocial_${VERSION}_linux_amd64.tar.gz /src.tar.gz
RUN tar --no-same-owner -xvzf /src.tar.gz && \
    install -D --mode 0755 /src/gotosocial /build/usr/bin/gotosocial && \
    mkdir -p /build/usr/share/gotosocial && cp -R /src/web /build/usr/share/gotosocial/web

FROM docker.io/debian:bookworm-slim@sha256:88200866dfff7ea7f5cbcb6ec7c8a701889efe6fe859fe64d6990e4b07ea4171
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends curl
RUN adduser --system --group --uid 10000 --home /var/lib/gotosocial gotosocial

COPY --from=builder /build /
COPY container/config /etc/gotosocial
COPY container/run-gotosocial /run-gotosocial

EXPOSE 8080
ENTRYPOINT ["/run-gotosocial"]
