FROM docker.io/debian:bookworm-slim@sha256:ad86386827b083b3d71139050b47ffb32bbd9559ea9b1345a739b14fec2d9ecf
ARG VERSION=7.2.5 # renovate: datasource=github-releases depName=redis/redis

RUN apt-get update -y && apt-get install -y --no-install-recommends ca-certificates
ADD --chown=_apt https://packages.redis.io/gpg /etc/apt/trusted.gpg.d/redis.asc

RUN echo "deb https://packages.redis.io/deb bookworm main" > /etc/apt/sources.list.d/redis.list && \
    apt-get update && apt-get install -y --no-install-recommends redis-server="6:${VERSION}*"

COPY container/config /etc/redis
USER redis

EXPOSE 6379
ENTRYPOINT ["redis-server", "/etc/redis/redis.conf"]
