FROM docker.io/debian:bookworm-slim@sha256:155280b00ee0133250f7159b567a07d7cd03b1645714c3a7458b2287b0ca83cb
ARG VERSION=7.2.4 # renovate: datasource=github-releases depName=redis/redis

RUN apt-get update -y && apt-get install -y --no-install-recommends ca-certificates
ADD --chown=_apt https://packages.redis.io/gpg /etc/apt/trusted.gpg.d/redis.asc

RUN echo "deb https://packages.redis.io/deb bookworm main" > /etc/apt/sources.list.d/redis.list && \
    apt-get update && apt-get install -y --no-install-recommends redis-server="6:${VERSION}*"

COPY container/config /etc/redis
USER redis

EXPOSE 6379
ENTRYPOINT ["redis-server", "/etc/redis/redis.conf"]
