FROM docker.io/debian:bookworm-slim@sha256:ccb33c3ac5b02588fc1d9e4fc09b952e433d0c54d8618d0ee1afadf1f3cf2455
ARG VERSION=7.2.4 # renovate: datasource=github-releases depName=redis/redis

RUN apt-get update -y && apt-get install -y --no-install-recommends ca-certificates
ADD --chown=_apt https://packages.redis.io/gpg /etc/apt/trusted.gpg.d/redis.asc

RUN echo "deb https://packages.redis.io/deb bookworm main" > /etc/apt/sources.list.d/redis.list && \
    apt-get update && apt-get install -y --no-install-recommends redis-server="6:${VERSION}*"

COPY container/config /etc/redis
USER redis

EXPOSE 6379
ENTRYPOINT ["redis-server", "/etc/redis/redis.conf"]
