FROM docker.io/debian:bookworm-slim@sha256:1537a6a1cbc4b4fd401da800ee9480207e7dc1f23560c21259f681db56768f63 AS builder
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ca-certificates build-essential pkg-config git libevent-dev libssl-dev

ARG VERSION=4.6.3 # renovate: datasource=github-releases depName=coturn/coturn
RUN git clone --branch ${VERSION} --depth=1 https://github.com/coturn/coturn.git /src && \
    mkdir /build && cd /src && ./configure --prefix=/usr --turndbdir=/var/lib/coturn && \
    make && make install DESTDIR=/build

FROM docker.io/debian:bookworm-slim@sha256:1537a6a1cbc4b4fd401da800ee9480207e7dc1f23560c21259f681db56768f63
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    libevent-2.1 libevent-core-2.1 libevent-extra-2.1 libevent-openssl-2.1 libevent-pthreads-2.1 \
    libssl3

RUN adduser --system --group --uid 10000 --home /var/lib/coturn coturn

COPY --from=builder /build /
COPY container/config /etc/coturn
COPY container/run-coturn /run-coturn
COPY container/run-healthcheck /run-healthcheck

# STUN/TURN ports.
EXPOSE 3478 3478/udp 5349 5349/udp

# Alternative STUN/TURN ports.
EXPOSE 3479 3479/udp 5350 5350/udp

ENTRYPOINT ["/run-coturn"]
