FROM docker.io/debian:bookworm-slim@sha256:f80c45482c8d147da87613cb6878a7238b8642bcc24fc11bad78c7bec726f340
# renovate: datasource=repology depName=debian_12/dovecot versioning=loose
ARG VERSION=4.6.1

RUN apt-get update -y && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends coturn=${VERSION}* gettext ca-certificates

COPY container/config /etc/coturn
COPY container/run-coturn /run-coturn
COPY container/run-healthcheck /run-healthcheck

# STUN/TURN ports.
EXPOSE 3478 3478/udp 5349 5349/udp

# Alternative STUN/TURN ports.
EXPOSE 3479 3479/udp 5350 5350/udp

ENTRYPOINT ["/run-coturn"]
