FROM docker.io/debian:bookworm-slim@sha256:f9c6a2fd2ddbc23e336b6257a5245e31f996953ef06cd13a59fa0a1df2d5c252
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

ARG VERSION=1.30.0 # renovate: datasource=github-tags depName=nginx/nginx extractVersion=^release-(?<version>.*)$

ADD --chown=_apt https://nginx.org/keys/nginx_signing.key /etc/apt/trusted.gpg.d/nginx.asc
RUN echo "deb https://nginx.org/packages/mainline/debian bookworm nginx" > /etc/apt/sources.list.d/nginx.list && \
    apt-get update -y && apt-get install -y --no-install-recommends curl \
    nginx="${VERSION}*" nginx-module-xslt="${VERSION}*" && \
    rm -Rf /etc/nginx

RUN addgroup --system --gid 10000 nginx-shared
RUN gpasswd --add nginx nginx-shared

COPY container/config /etc/nginx
COPY container/run-nginx /run-nginx

RUN nginx -t

EXPOSE 80 443
STOPSIGNAL SIGQUIT

ENTRYPOINT ["/run-nginx"]
