FROM docker.io/debian:bookworm-slim@sha256:b1211f6d19afd012477bd34fdcabb6b663d680e0f4b0537da6e6b0fd057a3ec3
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

ARG VERSION=1.27.5 # renovate: datasource=github-tags depName=nginx/nginx extractVersion=^release-(?<version>.*)$

ADD --chown=_apt https://nginx.org/keys/nginx_signing.key /etc/apt/trusted.gpg.d/nginx.asc
RUN echo "deb https://nginx.org/packages/mainline/debian bookworm nginx" > /etc/apt/sources.list.d/nginx.list && \
    apt-get update -y && apt-get install -y --no-install-recommends curl \
    nginx="${VERSION}*" nginx-module-xslt="${VERSION}*" && \
    rm -Rf /etc/nginx

RUN addgroup --system --gid 10000 nginx-shared
RUN gpasswd --add nginx nginx-shared

COPY container/config /etc/nginx
COPY container/run-nginx /run-nginx

RUN nginx -t

EXPOSE 80 443
STOPSIGNAL SIGQUIT

ENTRYPOINT ["/run-nginx"]
