FROM docker.io/debian:bookworm-slim@sha256:7e490910eea2861b9664577a96b54ce68ea3e02ce7f51d89cb0103a6f9c386e0
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

ARG VERSION=3.13.0 # renovate: datasource=github-releases depName=rspamd/rspamd

ADD --chown=_apt https://rspamd.com/apt-stable/gpg.key /etc/apt/trusted.gpg.d/rspamd.asc
RUN echo "deb https://rspamd.com/apt-stable/ bookworm main" > /etc/apt/sources.list.d/rspamd.list && \
    apt-get update && apt-get install -y --no-install-recommends rspamd="${VERSION}*"

RUN adduser --system --group --uid 11332 --home /var/lib/rspamd rspamd

COPY container/config /etc/rspamd
COPY container/run-rspamd /run-rspamd

EXPOSE 11332 11333 11334
ENTRYPOINT ["/run-rspamd"]
