FROM docker.io/golang:1.16 AS builder
ARG VERSION=latest

RUN go install -v github.com/skx/rss2email@$VERSION

FROM docker.io/debian:stable-slim

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ca-certificates

RUN addgroup --system --gid 10000 rss2email
RUN adduser --system --uid 10000 --ingroup rss2email --home /var/lib/rss2email rss2email

COPY --from=builder /go/bin/rss2email /usr/bin/rss2email

USER rss2email
ENTRYPOINT ["rss2email"]
