FROM docker.io/debian:bookworm-slim@sha256:d5d3f9c23164ea16f31852f95bd5959aad1c5e854332fe00f7b3a20fcc9f635c AS builder
ARG VERSION=3.8.1 # renovate: datasource=github-releases depName=prometheus/prometheus extractVersion=^v(?<version>.*)$
WORKDIR /src

ADD https://github.com/prometheus/prometheus/releases/download/v${VERSION}/prometheus-${VERSION}.linux-amd64.tar.gz /src.tar.gz
RUN tar --no-same-owner --strip-components 1 -xvzf /src.tar.gz && \
    install -D --mode 0755 -t /build/usr/bin /src/prometheus /src/promtool

FROM docker.io/debian:bookworm-slim@sha256:d5d3f9c23164ea16f31852f95bd5959aad1c5e854332fe00f7b3a20fcc9f635c AS builder-node-exporter
ARG VERSION=1.10.2 # renovate: datasource=github-releases depName=prometheus/node_exporter
WORKDIR /src

ADD https://github.com/prometheus/node_exporter/releases/download/v${VERSION}/node_exporter-${VERSION}.linux-amd64.tar.gz /src.tar.gz
RUN tar --no-same-owner --strip-components 1 -xvzf /src.tar.gz && \
    install -D --mode 0755 /src/node_exporter /build/usr/bin/prometheus-node-exporter

FROM docker.io/golang:1.25-bookworm@sha256:09f53deea14d4019922334afe6258b7b776afc1d57952be2012f2c8c4076db05 AS builder-podman-exporter
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    libgpgme-dev libbtrfs-dev libdevmapper-dev libassuan-dev pkg-config

ARG VERSION=1.20.0 # renovate: datasource=github-releases depName=containers/prometheus-podman-exporter extractVersion=^v(?<version>.*)$
WORKDIR /src

RUN git clone --branch v${VERSION} --depth 1 https://github.com/containers/prometheus-podman-exporter.git /src && make binary && \
    install -D --mode 0755 /src/bin/prometheus-podman-exporter /build/usr/bin/prometheus-podman-exporter

FROM docker.io/golang:1.25-bookworm@sha256:09f53deea14d4019922334afe6258b7b776afc1d57952be2012f2c8c4076db05 AS builder-smartctl-exporter
ARG VERSION=0.14.0 # renovate: datasource=github-releases depName=prometheus-community/smartctl_exporter extractVersion=^v(?<version>.*)$

RUN GOBIN=/src/bin go install github.com/prometheus-community/smartctl_exporter@v${VERSION} && \
    install -D --mode 0755 /src/bin/smartctl_exporter /build/usr/bin/prometheus-smartctl-exporter

FROM docker.io/debian:bookworm-slim@sha256:d5d3f9c23164ea16f31852f95bd5959aad1c5e854332fe00f7b3a20fcc9f635c
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    curl libgpgme11 libbtrfs0 libdevmapper1.02.1 libassuan0 smartmontools

RUN adduser --system --group --uid 10000 --home /var/lib/prometheus prometheus

COPY --from=builder /build /
COPY --from=builder-node-exporter /build /
COPY --from=builder-podman-exporter /build /
COPY --from=builder-smartctl-exporter /build /

COPY container/config /etc/prometheus
USER prometheus

ENTRYPOINT ["/usr/bin/prometheus", "--config.file=/etc/prometheus/prometheus.yml", \
                                   "--storage.tsdb.path=/var/lib/prometheus", \
                                   "--web.console.templates=/opt/prometheus/consoles", \
                                   "--web.console.libraries=/opt/prometheus/console_libraries"]
