FROM docker.io/debian:bookworm-slim@sha256:f4a83aa865a2b4a064ff142aa91c713180df9fcb86ce676b5de2981029379c37 AS builder
ARG VERSION=2.49.1 # renovate: datasource=github-releases depName=prometheus/prometheus extractVersion=^v(?<version>.*)$
WORKDIR /src

ADD https://github.com/prometheus/prometheus/releases/download/v${VERSION}/prometheus-${VERSION}.linux-amd64.tar.gz /src.tar.gz
RUN tar --no-same-owner --strip-components 1 -xvzf /src.tar.gz && \
    install -D --mode 0755 -t /build/usr/bin /src/prometheus /src/promtool

FROM docker.io/debian:bookworm-slim@sha256:f4a83aa865a2b4a064ff142aa91c713180df9fcb86ce676b5de2981029379c37 AS builder-node-exporter
ARG VERSION=1.7.0 # renovate: datasource=github-releases depName=prometheus/node_exporter
WORKDIR /src

ADD https://github.com/prometheus/node_exporter/releases/download/v${VERSION}/node_exporter-${VERSION}.linux-amd64.tar.gz /src.tar.gz
RUN tar --no-same-owner --strip-components 1 -xvzf /src.tar.gz && \
    install -D --mode 0755 /src/node_exporter /build/usr/bin/prometheus-node-exporter

FROM docker.io/golang:1.21-bookworm@sha256:d8c365d63879c2312e332cb796961f2695dd65124ceb3c0247d9c5426b7dde5f AS builder-podman-exporter
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    libgpgme-dev libbtrfs-dev libdevmapper-dev libassuan-dev pkg-config

ARG VERSION=1.7.0 # renovate: datasource=github-releases depName=containers/prometheus-podman-exporter extractVersion=^v(?<version>.*)$
WORKDIR /src

RUN git clone --branch v${VERSION} --depth 1 https://github.com/containers/prometheus-podman-exporter.git /src && make binary && \
    install -D --mode 0755 /src/bin/prometheus-podman-exporter /build/usr/bin/prometheus-podman-exporter

FROM docker.io/golang:1.21-bookworm@sha256:d8c365d63879c2312e332cb796961f2695dd65124ceb3c0247d9c5426b7dde5f AS builder-smartctl-exporter
ARG VERSION=0.11.0 # renovate: datasource=github-releases depName=prometheus-community/smartctl_exporter extractVersion=^v(?<version>.*)$

RUN GOBIN=/src/bin go install github.com/prometheus-community/smartctl_exporter@v${VERSION} && \
    install -D --mode 0755 /src/bin/smartctl_exporter /build/usr/bin/prometheus-smartctl-exporter

FROM docker.io/debian:bookworm-slim@sha256:f4a83aa865a2b4a064ff142aa91c713180df9fcb86ce676b5de2981029379c37
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    curl libgpgme11 libbtrfs0 libdevmapper1.02.1 libassuan0 smartmontools

RUN adduser --system --group --uid 10000 --home /var/lib/prometheus prometheus

COPY --from=builder /build /
COPY --from=builder-node-exporter /build /
COPY --from=builder-podman-exporter /build /
COPY --from=builder-smartctl-exporter /build /

COPY container/config /etc/prometheus
USER prometheus

ENTRYPOINT ["/usr/bin/prometheus", "--config.file=/etc/prometheus/prometheus.yml", \
                                   "--storage.tsdb.path=/var/lib/prometheus", \
                                   "--web.console.templates=/opt/prometheus/consoles", \
                                   "--web.console.libraries=/opt/prometheus/console_libraries"]
