FROM docker.io/debian:bookworm-slim@sha256:40b107342c492725bc7aacbe93a49945445191ae364184a6d24fedb28172f6f7
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    curl mercurial apt-transport-https

RUN adduser --system --group --uid 10000 --home /var/lib/prosody prosody && \
    install --owner prosody --group prosody --directory /run/prosody

ARG VERSION=0.12.5-1~bookworm1 # renovate: datasource=deb depName=prosody registryUrl=https://packages.prosody.im/debian?release=bookworm&components=main&binaryArch=amd64
ADD --chown=_apt https://prosody.im/files/prosody-debian-packages.key /etc/apt/trusted.gpg.d/prosody.gpg
RUN echo "deb https://packages.prosody.im/debian bookworm main" > /etc/apt/sources.list.d/prosody.list && \
    apt-get update -y && apt-get install -y --no-install-recommends \
    prosody=${VERSION}* lua5.2 lua-dbi-sqlite3 lua-zlib lua-sec lua-luaossl lua-bitop lua-unbound lua-ldap

ARG MODULES_VERSION=0ee77be396b9
RUN install -d /usr/lib/prosody/community-modules && \
    hg clone --rev ${MODULES_VERSION} https://hg.prosody.im/prosody-modules /usr/lib/prosody/community-modules

COPY container/config /etc/prosody
RUN prosodyctl check config

VOLUME /var/lib/prosody
USER prosody

ENTRYPOINT ["prosody"]
