#!/bin/sh
set -eu

# Correct permissions where needed.
chown -R biboumi:biboumi /var/lib/biboumi

# Prepare configuration files for environment variable substitution.
ENV_NAMES="$(env | awk -F '=' '{printf "$%s ", $1}')"
for file in /etc/biboumi/*.template; do
	envsubst "$ENV_NAMES" < "$file" > "${file%.template}"
done

gosu biboumi /usr/bin/biboumi /etc/biboumi/biboumi.cfg "$@"
