FROM docker.io/debian:bookworm-slim@sha256:4724b8cc51e33e398f0e2e15e18d5ec2851ff0c2280647e1310bc1642182655d AS builder
ARG VERSION=0.16.0 # renovate: datasource=github-releases depName=stalwartlabs/stalwart extractVersion=^v(?<version>.*)$

WORKDIR /src

ADD https://github.com/stalwartlabs/stalwart/releases/download/v${VERSION}/stalwart-x86_64-unknown-linux-gnu.tar.gz /src.tar.gz
ADD https://github.com/stalwartlabs/stalwart/releases/download/v${VERSION}/stalwart-cli-x86_64-unknown-linux-gnu.tar.gz /cli.tar.gz

RUN tar --no-same-owner -xvzf /src.tar.gz && install -D --mode 0755 -t /build/usr/bin /src/stalwart
RUN tar --no-same-owner -xvzf /cli.tar.gz && install -D --mode 0755 -t /build/usr/bin /src/stalwart-cli

FROM docker.io/debian:bookworm-slim@sha256:4724b8cc51e33e398f0e2e15e18d5ec2851ff0c2280647e1310bc1642182655d
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu curl

RUN adduser --system --group --uid 10000 --home /var/lib/stalwart stalwart

COPY --from=builder /build /
COPY container/config /etc/stalwart

USER stalwart
ENTRYPOINT ["stalwart", "--config", "/etc/stalwart/config.toml"]
