#!/bin/sh

set -eu

# Initialize configuration for Gitea Actions.
envsubst < /etc/gitea/actions.yaml.template > /etc/gitea/actions.yaml

# Create data directories and correct permissions for data files.
chown -R git:git /var/lib/gitea-actions

# Initialize token for Gitea Actions in shared volume.
if ! test -f /var/lib/gitea-actions/runner-global; then
    gosu git /usr/bin/act_runner --config /etc/gitea/actions.yaml register \
        --no-interactive \
        --name "actions-global" \
        --instance "https://${GITEA_DOMAIN}" \
        --token "$(cat /etc/gitea/runner-token)"
fi

# Run entrypoint under specific user.
exec gosu git /usr/bin/act_runner --config /etc/gitea/actions.yaml daemon "$@"
