#!/bin/sh

# Set NGINX resolver from system-wide configuration.
awk '/^nameserver/ {printf "resolver %s valid=60s ipv6=off;\n", $2; exit}' /etc/resolv.conf > /etc/nginx/resolver.conf

# Start NGINX as foreground process.
nginx -g 'daemon off;'
