FROM docker.io/debian:bookworm-slim@sha256:d02c76d82364cedca16ba3ed6f9102406fa9fa8833076a609cabf14270f43dfc AS builder-hugo
ARG VERSION=0.123.7 # renovate: datasource=github-releases depName=gohugoio/hugo extractVersion=^v(?<version>.*)$

WORKDIR /src

ADD https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_${VERSION}_Linux-64bit.tar.gz /src.tar.gz
RUN tar --no-same-owner -xvzf /src.tar.gz && \
    install -D --mode 0755 /src/hugo /build/usr/bin/hugo

FROM docker.io/golang:1.22-bookworm@sha256:6699d2852712f090399ccd4e8dfd079b4d55376f3ab3aff5b2dc8b7b1c11e27e AS builder-webhook
ARG VERSION=2.8.1 # renovate: datasource=github-releases depName=adnanh/webhook

RUN GOBIN=/build/usr/bin go install github.com/adnanh/webhook@${VERSION}

FROM docker.io/debian:bookworm-slim@sha256:d02c76d82364cedca16ba3ed6f9102406fa9fa8833076a609cabf14270f43dfc
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends curl openssh-client git
RUN adduser --system --group --uid 10000 --no-create-home hugo

COPY --from=builder-hugo /build /
COPY --from=builder-webhook /build /
COPY container/config /etc/hugo
COPY container/run-hugo /run-hugo

ENTRYPOINT ["/run-hugo"]
