FROM docker.io/golang:1.21-bookworm AS builder

WORKDIR /build
ENV GOBIN=/build/bin

RUN go install github.com/adnanh/webhook@latest

FROM docker.io/debian:bookworm-slim
ARG VERSION=0.119.0

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ca-certificates curl git gettext gosu openssh-client

RUN curl -L https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_${VERSION}_Linux-64bit.tar.gz | \
            tar -C /bin --no-same-owner -xvzf - hugo && chmod +x /bin/hugo

RUN addgroup --system --gid 10000 hugo
RUN adduser --system --uid 10000 --ingroup hugo --no-create-home hugo

COPY --from=builder /build/bin/webhook /bin/webhook
COPY container/config /etc/hugo
COPY container/run-hugo /run-hugo

ENTRYPOINT ["/run-hugo"]
