FROM docker.io/debian:bookworm-slim@sha256:ad86386827b083b3d71139050b47ffb32bbd9559ea9b1345a739b14fec2d9ecf AS builder-base

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ca-certificates git curl python3 python3-pip python3-venv

ENV PATH=/venv/bin:/root/.local/bin:$PATH
RUN python3 -m venv /venv && python3 -m pip install wheel
RUN curl -fL https://install.python-poetry.org | python3 -

FROM builder-base AS builder-discord

ARG VERSION=095eba37fa63591adc35adcb228e75ce79bf6717 # renovate: datasource=git-refs depName=slidcord packageName=https://git.sr.ht/~nicoco/slidcord versioning=git
RUN git clone https://git.sr.ht/~nicoco/slidcord /src && \
    cd /src && git reset --hard ${VERSION}

RUN cd /src && poetry export --without-hashes > requirements.txt && \
    python3 -m pip install --requirement requirements.txt

RUN cp -R /src/slidcord /venv/lib/python3.11/site-packages/legacy_module

FROM builder-base AS builder-skype

ARG VERSION=8f40deeb8dc8663cdbb12cb3b68be4b60fb8c85c # renovate: datasource=git-refs depName=skidge packageName=https://git.sr.ht/~nicoco/skidge versioning=git
RUN git clone https://git.sr.ht/~nicoco/skidge /src && \
    cd /src && git reset --hard ${VERSION}

RUN cd /src && poetry export --without-hashes > requirements.txt && \
    python3 -m pip install --requirement requirements.txt

RUN cp -R /src/skidge /venv/lib/python3.11/site-packages/legacy_module

FROM builder-base AS builder-whatsapp

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    gcc python3-dev

RUN echo "deb http://deb.debian.org/debian bookworm-backports main" > /etc/apt/sources.list.d/backports.list && \
    apt-get update -y && apt-get install -y --no-install-recommends -t bookworm-backports golang

ENV GOBIN=/usr/bin
RUN go install github.com/go-python/gopy@latest && \
    go install golang.org/x/tools/cmd/goimports@latest

RUN python3 -m pip install pybindgen

ARG VERSION=b3831cb3c0692945998e5eaddd1c4d230097d5aa # renovate: datasource=git-refs depName=slidge-whatsapp packageName=https://git.sr.ht/~nicoco/slidge-whatsapp versioning=git
RUN git clone https://git.sr.ht/~nicoco/slidge-whatsapp /src && \
    cd /src && git reset --hard ${VERSION}

RUN cd /src && poetry export --without-hashes > requirements.txt && \
    python3 -m pip install --requirement requirements.txt

RUN cd /src/slidge_whatsapp && gopy build -vm=python3 -output=generated -no-make=true .
RUN cp -R /src/slidge_whatsapp /venv/lib/python3.11/site-packages/legacy_module

FROM docker.io/debian:bookworm-slim@sha256:ad86386827b083b3d71139050b47ffb32bbd9559ea9b1345a739b14fec2d9ecf
ENV PYTHONUNBUFFERED=1
ENV SLIDGE_LEGACY_MODULE=legacy_module

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ca-certificates python3 libpython3.11 python3-gdbm libidn12 libmagic1 media-types shared-mime-info \
    ffmpeg

RUN addgroup --system --gid 10000 slidge
RUN adduser --system --uid 10000 --ingroup slidge --home /var/lib/slidge slidge

COPY --from=builder-discord /venv /venv/discord
COPY --from=builder-skype /venv /venv/skype
COPY --from=builder-whatsapp /venv /venv/whatsapp

USER slidge
