FROM docker.io/debian:trixie-slim@sha256:9b6ccd28f4913155f35e10ecd4437347d86ebce4ecf5853b3568141468faec56 AS builder-base

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ca-certificates git curl python3 python3-pip python3-venv

ENV PATH=/venv/bin:/root/.local/bin:$PATH
ENV UV_PROJECT_ENVIRONMENT=/venv/

RUN python3 -m venv /venv && python3 -m pip install wheel && \
    python3 -m pip install uv

FROM builder-base AS builder-go

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    gcc golang python3-dev

ENV GOBIN=/usr/bin
RUN go install github.com/go-python/gopy@master && \
    go install golang.org/x/tools/cmd/goimports@master

FROM builder-base AS builder-discord

WORKDIR /src

ARG VERSION=0.3.0 # renovate: datasource=git-tags depName=slidcord packageName=https://codeberg.org/slidge/slidcord extractVersion=^v(?<version>.*)$
RUN git clone https://codeberg.org/slidge/slidcord.git /src && \
    git reset --hard v${VERSION}

RUN uv sync --no-dev
RUN cp -R /src/slidcord /venv/lib/python3.13/site-packages/legacy_module

FROM builder-go AS builder-whatsapp

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    libmupdf-dev libgumbo-dev libfreetype6-dev libharfbuzz-dev libjbig2dec0-dev libjpeg62-turbo-dev \
    libmujs-dev libopenjp2-7-dev

WORKDIR /src

ARG VERSION=0.3.7 # renovate: datasource=git-tags depName=slidge-whatsapp packageName=https://codeberg.org/slidge/slidge-whatsapp extractVersion=^v(?<version>.*)$
RUN git clone https://codeberg.org/slidge/slidge-whatsapp.git /src && \
    git reset --hard v${VERSION}

RUN uv sync --no-dev
RUN uv pip install pybindgen

WORKDIR /src/slidge_whatsapp

RUN gopy build -vm=python3 -output=generated -no-make=true -build-tags="mupdf extlib" .
RUN cp -R /src/slidge_whatsapp /venv/lib/python3.13/site-packages/legacy_module

FROM builder-go AS builder-signal

WORKDIR /src

ARG VERSION=0.3.0beta5 # renovate: datasource=git-tags depName=slidgnal packageName=https://codeberg.org/slidge/slidgnal extractVersion=^v(?<version>.*)$
RUN git clone https://codeberg.org/slidge/slidgnal.git /src && \
    git reset --hard v${VERSION}

ARG SIGNAL_FFI_IMAGE=dock.mau.dev/tulir/gomuks-build-docker/signal:linux-amd64@sha256:987ea6c5e8c84e3a1859a108a1687ef6a6dcf7f2df1274ff003cb5870399efe8
COPY --from=$SIGNAL_FFI_IMAGE /usr/lib/libsignal_ffi.a /usr/lib/libsignal_ffi.a

RUN uv sync --no-dev
RUN uv pip install pybindgen

WORKDIR /src/slidgnal

RUN gopy build -vm=python3 -output=generated -no-make=true .
RUN cp -R /src/slidgnal /venv/lib/python3.13/site-packages/legacy_module

FROM docker.io/debian:trixie-slim@sha256:9b6ccd28f4913155f35e10ecd4437347d86ebce4ecf5853b3568141468faec56
ENV PYTHONUNBUFFERED=1
ENV SLIDGE_LEGACY_MODULE=legacy_module

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ca-certificates python3 libpython3.13 python3-gdbm libidn12 libmagic1 libmupdf25.1 \
    media-types shared-mime-info ffmpeg

RUN groupadd --system --gid 10000 slidge && \
    useradd --system --uid 10000 --gid 10000 --base-dir /var/lib/slidge slidge

COPY --from=builder-discord /venv /venv/discord
COPY --from=builder-whatsapp /venv /venv/whatsapp
COPY --from=builder-signal /venv /venv/signal

WORKDIR /var/lib/slidge
USER slidge
