FROM docker.io/debian:bookworm-slim@sha256:5f7d5664eae4a192c2d2d6cb67fc3f3c7891a8722cd2903cc35aa649a12b0c8d AS builder-base

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ca-certificates git curl python3 python3-pip python3-venv

ENV PATH=/venv/bin:/root/.local/bin:$PATH
RUN python3 -m venv /venv && python3 -m pip install wheel
RUN curl -fL https://install.python-poetry.org | python3 -

FROM builder-base AS builder-discord

ARG VERSION=05c935e8116deed127cd530051ef984320198b16 # renovate: datasource=git-refs depName=slidcord packageName=https://git.sr.ht/~nicoco/slidcord versioning=git
RUN git clone https://git.sr.ht/~nicoco/slidcord /src && \
    cd /src && git reset --hard ${VERSION}

RUN cd /src && poetry export --without-hashes > requirements.txt && \
    python3 -m pip install --requirement requirements.txt

RUN cp -R /src/slidcord /venv/lib/python3.11/site-packages/legacy_module

FROM builder-base AS builder-skype

ARG VERSION=e200ad614d480e246c5d1ca25d50e938f2ba2aee # renovate: datasource=git-refs depName=skidge packageName=https://git.sr.ht/~nicoco/skidge versioning=git
RUN git clone https://git.sr.ht/~nicoco/skidge /src && \
    cd /src && git reset --hard ${VERSION}

RUN cd /src && poetry export --without-hashes > requirements.txt && \
    python3 -m pip install --requirement requirements.txt

RUN cp -R /src/skidge /venv/lib/python3.11/site-packages/legacy_module

FROM builder-base AS builder-whatsapp

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    gcc python3-dev

RUN echo "deb http://deb.debian.org/debian bookworm-backports main" > /etc/apt/sources.list.d/backports.list && \
    apt-get update -y && apt-get install -y --no-install-recommends -t bookworm-backports golang

ENV GOBIN=/usr/bin
RUN go install github.com/go-python/gopy@latest && \
    go install golang.org/x/tools/cmd/goimports@latest

RUN python3 -m pip install pybindgen

ARG VERSION=1275ef55d1737b74eb0d419779d08fc85f37f970 # renovate: datasource=git-refs depName=slidge-whatsapp packageName=https://git.sr.ht/~nicoco/slidge-whatsapp versioning=git
RUN git clone https://git.sr.ht/~nicoco/slidge-whatsapp /src && \
    cd /src && git reset --hard ${VERSION}

RUN cd /src && poetry export --without-hashes > requirements.txt && \
    python3 -m pip install --requirement requirements.txt

RUN cd /src/slidge_whatsapp && gopy build -vm=python3 -output=generated -no-make=true .
RUN cp -R /src/slidge_whatsapp /venv/lib/python3.11/site-packages/legacy_module

FROM docker.io/debian:bookworm-slim@sha256:5f7d5664eae4a192c2d2d6cb67fc3f3c7891a8722cd2903cc35aa649a12b0c8d
ENV PYTHONUNBUFFERED=1
ENV SLIDGE_LEGACY_MODULE=legacy_module

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ca-certificates python3 libpython3.11 python3-gdbm libidn12 libmagic1 media-types shared-mime-info \
    ffmpeg

RUN addgroup --system --gid 10000 slidge
RUN adduser --system --uid 10000 --ingroup slidge --home /var/lib/slidge slidge

COPY --from=builder-discord /venv /venv/discord
COPY --from=builder-skype /venv /venv/skype
COPY --from=builder-whatsapp /venv /venv/whatsapp

USER slidge
