#!/bin/sh

# Prepare configuration files for environment variable substitution.
ENV_NAMES="`env | awk -F '=' '{printf "$%s ", $1}'`"
for file in /etc/postfix/*.template; do
	envsubst "${ENV_NAMES}" < "$file" > "`echo $file | awk -F '.template$' '{print $1}'`"
done

# Generate local aliases and virtual maps.
postalias /etc/postfix/aliases

# Ensure local files are correctly configured.
postfix set-permissions

# Run master daemon for Postfix.
/usr/sbin/postfix -c /etc/postfix start-fg
