FROM docker.io/debian:bookworm-slim@sha256:f4a83aa865a2b4a064ff142aa91c713180df9fcb86ce676b5de2981029379c37
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    curl netcat-traditional

ARG VERSION=2.3.19 # renovate: datasource=repology depName=debian_12/dovecot versioning=loose
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    dovecot-imapd=1:${VERSION}* dovecot-lmtpd=1:${VERSION}* dovecot-mysql=1:${VERSION}* \
    dovecot-sieve=1:${VERSION}* dovecot-managesieved=1:${VERSION}* dovecot-fts-xapian && \
    rm -Rf /etc/dovecot

RUN adduser --system --group --uid 5000 --home /var/mail/virtual virtual

COPY container/config /etc/dovecot
COPY container/run-dovecot /run-dovecot

EXPOSE 24 143 993 3659 4190
ENTRYPOINT ["/run-dovecot"]
