FROM docker.io/debian:bookworm-slim@sha256:40b107342c492725bc7aacbe93a49945445191ae364184a6d24fedb28172f6f7
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

ARG VERSION=7.3.2+ds-1~bpo12+1 # renovate: datasource=repology depName=debian_12_backports/redict versioning=loose
RUN echo "deb http://deb.debian.org/debian bookworm-backports main" > /etc/apt/sources.list.d/backports.list && \
    apt-get update -y && apt-get install -y --no-install-recommends -t bookworm-backports \
    redict-server="${VERSION}*"

COPY container/config /etc/redict
USER redict

EXPOSE 6379
ENTRYPOINT ["redict-server", "/etc/redict/redict.conf"]
