FROM docker.io/debian:bookworm-slim@sha256:d5d3f9c23164ea16f31852f95bd5959aad1c5e854332fe00f7b3a20fcc9f635c
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

ARG VERSION=7.3.6+ds-1~bpo12+1 # renovate: datasource=repology depName=debian_12_backports/redict versioning=loose
RUN echo "deb http://deb.debian.org/debian bookworm-backports main" > /etc/apt/sources.list.d/backports.list && \
    apt-get update -y && apt-get install -y --no-install-recommends -t bookworm-backports \
    redict-server="${VERSION}*"

COPY container/config /etc/redict
USER redict

EXPOSE 6379
ENTRYPOINT ["redict-server", "/etc/redict/redict.conf"]
