#!/bin/sh
set -eu

# Prepare configuration files for environment variable substitution.
ENV_NAMES="$(env | awk -F '=' '{printf "$%s ", $1}')"
for file in /etc/coturn/*.template; do
	envsubst "$ENV_NAMES" < "$file" > "${file%.template}"
done

/usr/bin/turnserver -c /etc/coturn/turnserver.conf
