#!/bin/sh
set -eu

# Correct permissions where needed.
chown -R coturn:coturn /var/lib/coturn

# Prepare configuration files for environment variable substitution.
ENV_NAMES="$(env | awk -F '=' '{printf "$%s ", $1}')"
for file in /etc/coturn/*.template; do
	envsubst "$ENV_NAMES" < "$file" > "${file%.template}"
done

exec /usr/bin/turnserver -c /etc/coturn/turnserver.conf
