FROM docker.io/debian:bookworm-slim
# renovate: datasource=repology depName=debian_12/dovecot versioning=loose
ARG VERSION=9.0

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu biboumi=${VERSION}*

RUN addgroup --system --gid 10000 biboumi
RUN adduser --system --uid 10000 --ingroup biboumi --home /var/lib/biboumi biboumi

COPY container/config /etc/biboumi
COPY container/run-biboumi /run-biboumi

ENTRYPOINT ["/run-biboumi"]
