FROM docker.io/debian:bookworm-slim@sha256:78d2f66e0fec9e5a39fb2c72ea5e052b548df75602b5215ed01a17171529f706 AS builder
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ca-certificates build-essential cmake git libexpat1-dev libidn11-dev uuid-dev \
    libsqlite3-dev libudns-dev libbotan-2-dev

ARG VERSION=9.0 # renovate: datasource=github-tags depName=louiz/biboumi
RUN git clone --branch ${VERSION} https://github.com/louiz/biboumi.git /src && \
    mkdir /src/build /build && cd /src/build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DWITH_BOTAN=1 -DWITH_SQLITE3=1 \
             -DWITH_LIBIDN=1 -DWITHOUT_SYSTEMD=1 -Wno-dev && \
    make && make install DESTDIR=/build

FROM docker.io/debian:bookworm-slim@sha256:78d2f66e0fec9e5a39fb2c72ea5e052b548df75602b5215ed01a17171529f706
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    libexpat1 libidn12 libuuid1 libsqlite3-0 libudns0 libbotan-2-19

RUN adduser --system --group --uid 10000 --home /var/lib/biboumi biboumi

COPY --from=builder /build /
COPY container/config /etc/biboumi
COPY container/run-biboumi /run-biboumi

ENTRYPOINT ["/run-biboumi"]
