FROM docker.io/debian:bookworm-slim@sha256:0104b334637a5f19aa9c983a91b54c89887c0984081f2068983107a6f6c21eeb
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    python3 python3-pip python3-venv python3-pytz-deprecation-shim curl

ARG VERSION=3.7.3 # renovate: datasource=github-releases depName=Kozea/Radicale extractVersion=^v(?<version>.*)$
RUN python3 -m venv /venv && \
    /venv/bin/pip install ldap3 && \
    /venv/bin/pip install https://github.com/Kozea/Radicale/archive/v${VERSION}.tar.gz

RUN adduser --system --group --uid 10000 --home /var/lib/radicale radicale

COPY container/config /etc/radicale
COPY container/run-radicale /run-radicale

EXPOSE 5232
ENTRYPOINT ["/run-radicale"]
