FROM docker.io/debian:bookworm-slim@sha256:cfa4fa03c2133b9e3f5dbd6ae601036c5a966ce0b4a5e3b264607ffc1e320fb3
ARG VERSION=d7ce2f0b98589400b0e1718cfd7bb29b7ebeaebe

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    python3 python3-pip python3-venv gettext curl

RUN python3 -m venv /venv && \
    /venv/bin/pip install https://github.com/Kozea/Radicale/archive/${VERSION}.tar.gz && \
    /venv/bin/pip install --no-deps https://github.com/Unrud/RadicaleIMAP/archive/master.tar.gz

RUN addgroup --system --gid 15232 radicale
RUN adduser --system --uid 15232 --ingroup radicale --home /var/lib/radicale radicale

COPY --chown=radicale:radicale container/config /etc/radicale
COPY container/run-radicale /run-radicale

USER radicale
EXPOSE 5232

ENTRYPOINT ["/run-radicale"]
