FROM docker.io/debian:bookworm-slim@sha256:d365f4920711a9074c4bcd178e8f457ee59250426441ab2a5f8106ed8fe948eb
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    python3 python3-pip python3-venv python3-pytz-deprecation-shim curl

ARG VERSION=3.3.3 # renovate: datasource=github-releases depName=Kozea/Radicale extractVersion=^v(?<version>.*)$
RUN python3 -m venv /venv && \
    /venv/bin/pip install ldap3 && \
    /venv/bin/pip install https://github.com/Kozea/Radicale/archive/v${VERSION}.tar.gz

RUN adduser --system --group --uid 10000 --home /var/lib/radicale radicale

COPY container/config /etc/radicale
COPY container/run-radicale /run-radicale

EXPOSE 5232
ENTRYPOINT ["/run-radicale"]
