FROM docker.io/debian:bookworm-slim@sha256:804194b909ef23fb995d9412c9378fb3505fe2427b70f3cc425339e48a828fca
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

ARG VERSION=3.7.10-0+deb12u1 # renovate: datasource=repology depName=debian_12/postfix versioning=loose
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    postfix=${VERSION}* postfix-mysql=${VERSION}* syslog-ng-core netcat-traditional

COPY container/config /etc/postfix
COPY container/run-postfix /run-postfix

RUN adduser --system --group --uid 5000 --home /var/mail/virtual virtual

EXPOSE 25 465 587
ENTRYPOINT ["/run-postfix"]
