FROM docker.io/debian:bookworm-slim@sha256:4d9b5b6cf5f643fdf2887eab79f2f916363704184ab270bf4a5c1d65102d03d2
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

ARG VERSION=3.7.11-0+deb12u1 # renovate: datasource=repology depName=debian_12/postfix versioning=loose
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    postfix=${VERSION}* postfix-mysql=${VERSION}* syslog-ng-core netcat-traditional

COPY container/config /etc/postfix
COPY container/run-postfix /run-postfix
COPY container/run-healthcheck /run-healthcheck

RUN adduser --system --group --uid 5000 --home /var/mail/virtual virtual

EXPOSE 25 465 587
ENTRYPOINT ["/run-postfix"]
