FROM docker.io/debian:bookworm-slim@sha256:56ff6d36d4eb3db13a741b342ec466f121480b5edded42e4b7ee850ce7a418ee
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

ARG VERSION=3.7.11-0+deb12u1 # renovate: datasource=repology depName=debian_12/postfix versioning=loose
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    postfix=${VERSION}* postfix-mysql=${VERSION}* syslog-ng-core netcat-traditional

COPY container/config /etc/postfix
COPY container/run-postfix /run-postfix
COPY container/run-healthcheck /run-healthcheck

RUN adduser --system --group --uid 5000 --home /var/mail/virtual virtual

EXPOSE 25 465 587
ENTRYPOINT ["/run-postfix"]
