FROM docker.io/debian:bookworm-slim@sha256:5f7d5664eae4a192c2d2d6cb67fc3f3c7891a8722cd2903cc35aa649a12b0c8d AS builder-gitea
ARG VERSION=1.22.1 # renovate: datasource=github-releases depName=go-gitea/gitea extractVersion=^v(?<version>.*)$

ADD https://dl.gitea.io/gitea/${VERSION}/gitea-${VERSION}-linux-amd64 /src/gitea
RUN install -D --mode 0755 /src/gitea /build/usr/bin/gitea

FROM docker.io/golang:1.22-bookworm@sha256:6c2780255bb7b881e904e303be0d7a079054160b2ce1efde446693c0850a39ad AS builder-act-runner
ARG VERSION=0.2.10 # renovate: datasource=gitea-releases depName=gitea/act_runner extractVersion=^v(?<version>.*)$

ADD https://dl.gitea.com/act_runner/${VERSION}/act_runner-${VERSION}-linux-amd64 /src/act_runner
RUN install -D --mode 0755 /src/act_runner /build/usr/bin/act_runner

FROM docker.io/debian:bookworm-slim@sha256:5f7d5664eae4a192c2d2d6cb67fc3f3c7891a8722cd2903cc35aa649a12b0c8d
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    curl git openssh-client gnupg

RUN adduser --system --group --uid 10000 --home /var/lib/gitea git

COPY --from=builder-gitea /build /
COPY --from=builder-act-runner /build /
COPY container/config /etc/gitea
COPY container/run-gitea /run-gitea
COPY container/run-gitea-actions /run-gitea-actions

EXPOSE 8080 7920
ENTRYPOINT ["/run-gitea"]
