FROM docker.io/debian:bookworm-slim@sha256:a629e796d77a7b2ff82186ed15d01a493801c020eed5ce6adaa2704356f15a1c AS builder-gitea
ARG VERSION=1.22.2 # renovate: datasource=github-releases depName=go-gitea/gitea extractVersion=^v(?<version>.*)$

ADD https://dl.gitea.io/gitea/${VERSION}/gitea-${VERSION}-linux-amd64 /src/gitea
RUN install -D --mode 0755 /src/gitea /build/usr/bin/gitea

FROM docker.io/golang:1.23-bookworm@sha256:1a5326b07cbab12f4fd7800425f2cf25ff2bd62c404ef41b56cb99669a710a83 AS builder-act-runner
ARG VERSION=0.2.10 # renovate: datasource=gitea-releases depName=gitea/act_runner extractVersion=^v(?<version>.*)$

ADD https://dl.gitea.com/act_runner/${VERSION}/act_runner-${VERSION}-linux-amd64 /src/act_runner
RUN install -D --mode 0755 /src/act_runner /build/usr/bin/act_runner

FROM docker.io/debian:bookworm-slim@sha256:a629e796d77a7b2ff82186ed15d01a493801c020eed5ce6adaa2704356f15a1c
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    curl git openssh-client gnupg

RUN adduser --system --group --uid 10000 --home /var/lib/gitea git

COPY --from=builder-gitea /build /
COPY --from=builder-act-runner /build /
COPY container/config /etc/gitea
COPY container/run-gitea /run-gitea
COPY container/run-gitea-actions /run-gitea-actions

EXPOSE 8080 7920
ENTRYPOINT ["/run-gitea"]
