FROM docker.io/debian:bookworm-slim@sha256:7802002798b0e351323ed2357ae6dc5a8c4d0a05a57e7f4d8f97136151d3d603 AS builder
ARG VERSION=1.21.5 # renovate: datasource=github-releases depName=go-gitea/gitea extractVersion=^v(?<version>.*)$

ADD https://dl.gitea.io/gitea/${VERSION}/gitea-${VERSION}-linux-amd64 /src/gitea
RUN install -D --mode 0755 /src/gitea /build/usr/bin/gitea

FROM docker.io/debian:bookworm-slim@sha256:7802002798b0e351323ed2357ae6dc5a8c4d0a05a57e7f4d8f97136151d3d603
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    curl git openssh-client gnupg

RUN adduser --system --group --uid 10000 --home /var/lib/gitea git

COPY --from=builder /build /
COPY container/config /etc/gitea
COPY container/run-gitea /run-gitea

EXPOSE 8080 7920
ENTRYPOINT ["/run-gitea"]
