FROM docker.io/debian:bookworm-slim@sha256:0104b334637a5f19aa9c983a91b54c89887c0984081f2068983107a6f6c21eeb AS builder
ARG VERSION=0.6.3 # renovate: datasource=github-releases depName=lldap/lldap extractVersion=^v(?<version>.*)$

WORKDIR /src

ADD https://github.com/lldap/lldap/releases/download/v${VERSION}/amd64-lldap.tar.gz /src.tar.gz
RUN tar --no-same-owner --strip-components 1 -xvzf /src.tar.gz && \
    install -D --mode 0755 -t /build/usr/bin /src/lldap /src/lldap_migration_tool /src/lldap_set_password && \
    mkdir -p /build/usr/share/lldap/app && cp -R /src/app /build/usr/share/lldap

FROM docker.io/debian:bookworm-slim@sha256:0104b334637a5f19aa9c983a91b54c89887c0984081f2068983107a6f6c21eeb
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN adduser --system --group --uid 10000 --home /var/lib/lldap lldap

COPY --from=builder /build /
COPY container/config /etc/lldap
COPY container/run-lldap /run-lldap

EXPOSE 3890 8080
ENTRYPOINT ["/run-lldap"]
