FROM docker.io/debian:buster-slim
ARG VERSION=2.0.13

ENV BUILD_DEPS="curl gnupg apt-transport-https build-essential git libpurple-dev libglib2.0-dev libjson-glib-dev libhttp-parser-dev graphicsmagick-imagemagick-compat"

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends ca-certificates sudo gettext libjson-glib-1.0-0 ${BUILD_DEPS}

RUN echo "deb https://packages.spectrum.im/spectrum2/ buster main" > /etc/apt/sources.list.d/spectrum2.list && \
    echo "deb-src https://packages.spectrum.im/spectrum2/ buster main" >> /etc/apt/sources.list.d/spectrum2.list && \
    curl -o - https://packages.spectrum.im/packages.key | apt-key add - && \
    apt-get update -y && \
    apt-get install -y --no-install-recommends spectrum2=1:${VERSION}"*" spectrum2-backend-libpurple=1:${VERSION}"*"

RUN git clone https://github.com/EionRobb/skype4pidgin.git && \
    cd skype4pidgin/skypeweb && make && make install && \
    rm -Rf /skype4pidgin

RUN git clone https://github.com/dylex/slack-libpurple.git && \
    cd slack-libpurple && make && make install && \
    rm -Rf /slack-libpurple

RUN git clone https://github.com/EionRobb/purple-discord.git && \
    cd purple-discord && make && make install && \
    rm -Rf /purple-discord

RUN apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false ${BUILD_DEPS}

RUN addgroup --system --gid 10000 spectrum
RUN adduser --system --uid 10000 --ingroup spectrum --home /var/lib/spectrum2 spectrum

COPY container/config /etc/spectrum2
COPY container/run-spectrum /run-spectrum

ENTRYPOINT ["/run-spectrum"]
