#!/bin/sh

set -eu

# Copy certificates to dedicated directory.
install --owner letsencrypt --group letsencrypt --mode 0755 -d "/var/lib/letsencrypt-certificates/$LEGO_HOOK_CERT_NAME"
install --owner letsencrypt --group letsencrypt --mode 0644 "$LEGO_HOOK_CERT_PATH" "/var/lib/letsencrypt-certificates/$LEGO_HOOK_CERT_NAME/fullchain.pem"
install --owner letsencrypt --group letsencrypt --mode 0640 "$LEGO_HOOK_CERT_KEY_PATH" "/var/lib/letsencrypt-certificates/$LEGO_HOOK_CERT_NAME/privkey.pem"
