FROM docker.io/golang:1.22-bookworm@sha256:aec47843e52fee4436bdd3ce931417fa980e9055658b5142140925eea3044bea AS builder
ARG VERSION=aa3296fcc2883c345d3581ac670f652b2badedb5

RUN GOBIN=/build/usr/bin go install github.com/skx/rss2email@${VERSION}

FROM docker.io/debian:bookworm-slim@sha256:804194b909ef23fb995d9412c9378fb3505fe2427b70f3cc425339e48a828fca
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN adduser --system --group --uid 10000 --no-create-home rss2email

COPY --from=builder /build /
COPY container/run-rss2email /run-rss2email

ENTRYPOINT ["/run-rss2email"]
