FROM docker.io/debian:bullseye-slim
ARG VERSION=v3.14

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ca-certificates git gettext gosu \
    python3 python3-setuptools python3-feedparser python3-html2text python3-bs4

RUN git clone --branch ${VERSION} --depth 1 https://github.com/rss2email/rss2email /tmp/rss2email && \
    cd /tmp/rss2email && python3 setup.py install && \
    rm -Rf /tmp/rss2email

RUN addgroup --system --gid 10000 rss2email
RUN adduser --system --uid 10000 --ingroup rss2email --home /var/lib/rss2email rss2email

COPY container/config /etc/rss2email
COPY container/run-rss2email /run-rss2email

ENTRYPOINT ["/run-rss2email"]
