FROM docker.io/debian:bullseye-slim@sha256:b257e5e831aa9949737638f6d323cd563347b2a5571d98b9b15eef0c7cd80b68
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    git python3 python3-setuptools python3-feedparser python3-html2text python3-bs4

ARG VERSION=3.14 # renovate: datasource=github-tags depName=rss2email/rss2email extractVersion=^v(?<version>.*)$
RUN git clone --branch v${VERSION} --depth 1 https://github.com/rss2email/rss2email /src && \
    cd /src && python3 setup.py install

RUN adduser --system --group --uid 10000 --home /var/lib/rss2email rss2email

COPY container/config /etc/rss2email
COPY container/run-rss2email /run-rss2email

ENTRYPOINT ["/run-rss2email"]
