FROM docker.io/debian:bookworm-slim@sha256:5f7d5664eae4a192c2d2d6cb67fc3f3c7891a8722cd2903cc35aa649a12b0c8d AS builder
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ca-certificates build-essential flex bison pkg-config git libssl-dev libexpat1-dev libhiredis-dev

ARG VERSION=1.20.0 # renovate: datasource=github-releases depName=NLnetLabs/unbound extractVersion=^release-(?<version>.*)$
RUN git clone --branch release-${VERSION} --depth=1 https://github.com/NLnetLabs/unbound.git /src && \
    mkdir /build && cd /src && ./configure --prefix=/usr --enable-cachedb --with-libhiredis && \
    make && make install DESTDIR=/build

FROM docker.io/debian:bookworm-slim@sha256:5f7d5664eae4a192c2d2d6cb67fc3f3c7891a8722cd2903cc35aa649a12b0c8d
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    libssl3 libexpat1 libhiredis0.14 ldnsutils

RUN adduser --system --group --uid 10000 --home /var/lib/unbound unbound

COPY --from=builder /build /
COPY container/config /etc/unbound

ADD --chmod=0644 https://www.internic.net/domain/named.cache /etc/unbound/root.hints
RUN install -d --owner unbound --group unbound /etc/unbound/trust && gosu unbound unbound-anchor -a /etc/unbound/trust/root.key || exit 0
RUN unbound-checkconf /etc/unbound/unbound.conf

ENTRYPOINT ["/usr/sbin/unbound", "-c", "/etc/unbound/unbound.conf"]
