{
 "title": "Prosody",
 "description": "Monitoring for Prosody, the XMPP server.",
 "tags": [
  "chat",
  "service",
  "public"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Running?",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{instance=\"prosody:5280\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Server Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prosody_mod_s2s__connections_inbound) + sum(prosody_mod_s2s__connections_outbound)"
    }
   ]
  },
  {
   "title": "Total Client Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prosody_mod_c2s__connections)"
    }
   ]
  },
  {
   "title": "Current Live MUCs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prosody_mod_muc__live_room) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Client Connections",
   "type": "timeseries",
   "description": "Client connections established against Prosody, by host and type.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(prosody_mod_c2s__connections) by (host, type)",
     "legendFormat": "{{host}} - {{type}}"
    }
   ]
  },
  {
   "title": "Inbound Server Connections",
   "type": "timeseries",
   "description": "Server connections established against Prosody, by host and IP family.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum(prosody_mod_s2s__connections_inbound) by (host, ip_family)",
     "legendFormat": "{{host}} - {{ip_family}}"
    }
   ]
  },
  {
   "title": "Outbound Server Connections",
   "type": "timeseries",
   "description": "Server connections established by Prosody, by host and IP family.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum(prosody_mod_s2s__connections_outbound) by (host, ip_family)",
     "legendFormat": "{{host}} - {{ip_family}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "HTTP File Uploads",
   "type": "heatmap",
   "description": "The number of HTTP file uploads processed, by size.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(prosody_mod_http_file_share__upload_bytes_bucket[2m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "HTTP Upload Daily Quota",
   "type": "bargauge",
   "description": "The cumulative size of HTTP uploads against the shared daily quota.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prosody_mod_http_file_share__upload_bytes_sum[24h])"
    }
   ]
  },
  {
   "title": "HTTP Upload Global Quota",
   "type": "bargauge",
   "description": "The cumulative size of HTTP uploads against the shared global quota.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prosody_mod_http_file_share__total_storage_bytes"
    }
   ]
  }
 ]
}