{
 "title": "Podman Metrics",
 "description": "Host-wide Podman container metrics",
 "tags": [
  "host",
  "podman",
  "internal"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Container Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "podman_container_info", "legendFormat": "__auto" },
    { "expr": "podman_container_state", "legendFormat": "__auto" },
    {
     "expr": "podman_container_mem_usage_bytes",
     "legendFormat": "__auto"
    },
    { "expr": "podman_container_exit_code", "legendFormat": "__auto" },
    {
     "expr": "time() - podman_container_started_seconds",
     "legendFormat": "__auto"
    },
    { "expr": "podman_container_pids", "legendFormat": "__auto" },
    {
     "expr": "podman_container_mem_usage_bytes / (podman_container_mem_limit_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total CPU of containers",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(podman_container_cpu_seconds_total[$__rate_interval])) / count(node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "sum by(name) (podman_container_info{name!~\".+infra\"} * on(id) group_right(name) rate(podman_container_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by(name) (podman_container_info{name!~\".+infra\"} * on(id) group_right(name) podman_container_mem_usage_bytes / 1024 /1024)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total memory of containers",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(podman_container_mem_usage_bytes) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(name) (podman_container_info{name!~\".+infra\"} * on(id) group_right(name) rate(podman_container_block_input_total[$__rate_interval]))",
     "legendFormat": "{{name}} in"
    },
    {
     "expr": "sum by(name) (podman_container_info{name!~\".+infra\"} * on(id) group_right(name) rate(podman_container_block_output_total[$__rate_interval])) * -1",
     "legendFormat": "{{name}} out"
    }
   ]
  },
  {
   "title": "Networking",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by(name) (podman_container_info{name!~\".+infra\"} * on(id) group_right(name) rate(podman_container_net_input_total[$__rate_interval]) * 8)",
     "legendFormat": "{{name}} in"
    },
    {
     "expr": "sum by(name) (podman_container_info{name!~\".+infra\"} * on(id) group_right(name) rate(podman_container_net_output_total[$__rate_interval]) * 8) * -1",
     "legendFormat": "{{name}} out"
    }
   ]
  },
  { "title": "Images", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Total Image Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(podman_image_size)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(podman_image_size) / sum(node_filesystem_size_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Image Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 30 },
   "targets": [
    { "expr": "podman_image_info", "legendFormat": "__auto" },
    {
     "expr": "podman_image_created_seconds * 1000",
     "legendFormat": "__auto"
    },
    { "expr": "podman_image_size", "legendFormat": "__auto" }
   ]
  }
 ]
}