FROM docker.io/debian:bullseye-slim
ARG VERSION=2.1.2

ARG SKYPE_VERSION=29c860170ca18c3f7f15b5ba7723e06ddc760361
ARG DISCORD_VERSION=1db1b78a23775be7d29c2c7528e150f7b8ba4dd0
ENV BUILD_DEPS="curl gnupg apt-transport-https build-essential git libpurple-dev libglib2.0-dev \
                libjson-glib-dev libhttp-parser-dev graphicsmagick-imagemagick-compat"

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends ca-certificates sudo gettext libjson-glib-1.0-0 ${BUILD_DEPS}

RUN echo "deb https://packages.spectrum.im/spectrum2/ bullseye main" > /etc/apt/sources.list.d/spectrum2.list && \
    echo "deb-src https://packages.spectrum.im/spectrum2/ bullseye main" >> /etc/apt/sources.list.d/spectrum2.list && \
    curl -o - https://packages.spectrum.im/packages.key | apt-key add - && \
    apt-get update -y && \
    apt-get install -y --no-install-recommends spectrum2=1:${VERSION}"*" spectrum2-backend-libpurple=1:${VERSION}"*"

RUN git clone https://github.com/EionRobb/skype4pidgin.git && \
    cd skype4pidgin/skypeweb && git checkout ${SKYPE_VERSION} && make && make install && \
    rm -Rf /skype4pidgin

RUN git clone https://github.com/EionRobb/purple-discord.git && \
    cd purple-discord && git checkout ${DISCORD_VERSION} && make && make install && \
    rm -Rf /purple-discord

RUN apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false ${BUILD_DEPS}

RUN addgroup --system --gid 10000 spectrum
RUN adduser --system --uid 10000 --ingroup spectrum --home /var/lib/spectrum2 spectrum

COPY container/config /etc/spectrum2
COPY container/run-spectrum /run-spectrum

ENTRYPOINT ["/run-spectrum"]
