FROM docker.io/debian:bookworm-slim@sha256:f80c45482c8d147da87613cb6878a7238b8642bcc24fc11bad78c7bec726f340
ARG VERSION=0.50.2 # renovate: datasource=github-releases depName=navidrome/navidrome

ENV PACKAGE_URL https://github.com/navidrome/navidrome/releases/download/v${VERSION}/navidrome_${VERSION}_linux_amd64.tar.gz
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    curl ca-certificates gosu ffmpeg && \
    curl -L ${PACKAGE_URL} | tar -C /bin --no-same-owner -xvzf - navidrome && chmod +x /bin/navidrome

RUN addgroup --system --gid 10000 navidrome
RUN adduser --system --uid 10000 --ingroup navidrome --home /var/lib/navidrome navidrome

COPY container/config /etc/navidrome
VOLUME /music

USER navidrome
EXPOSE 4533

ENTRYPOINT ["/bin/navidrome", "--configfile", "/etc/navidrome/navidrome.toml"]
