FROM docker.io/debian:bookworm-slim@sha256:804194b909ef23fb995d9412c9378fb3505fe2427b70f3cc425339e48a828fca AS builder
ARG VERSION=0.52.5 # renovate: datasource=github-releases depName=navidrome/navidrome extractVersion=^v(?<version>.*)$
WORKDIR /src

ADD https://github.com/navidrome/navidrome/releases/download/v${VERSION}/navidrome_${VERSION}_linux_amd64.tar.gz /src.tar.gz
RUN tar --no-same-owner -xvzf /src.tar.gz && \
    install -D --mode 0755 /src/navidrome /build/usr/bin/navidrome

FROM docker.io/debian:bookworm-slim@sha256:804194b909ef23fb995d9412c9378fb3505fe2427b70f3cc425339e48a828fca
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    curl ffmpeg

RUN adduser --system --group --uid 10000 --home /var/lib/navidrome navidrome

COPY --from=builder /build /
COPY container/config /etc/navidrome

VOLUME /music
EXPOSE 4533

USER navidrome
ENTRYPOINT ["/usr/bin/navidrome", "--configfile", "/etc/navidrome/navidrome.toml"]
