FROM docker.io/debian:bookworm-slim@sha256:56ff6d36d4eb3db13a741b342ec466f121480b5edded42e4b7ee850ce7a418ee
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    curl netcat-traditional

ARG VERSION=2.3.19 # renovate: datasource=repology depName=debian_12/dovecot versioning=loose
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    dovecot-imapd=1:${VERSION}* dovecot-lmtpd=1:${VERSION}* dovecot-mysql=1:${VERSION}* \
    dovecot-sieve=1:${VERSION}* dovecot-managesieved=1:${VERSION}* dovecot-fts-xapian && \
    rm -Rf /etc/dovecot

RUN adduser --system --group --uid 5000 --home /var/mail/virtual virtual

COPY container/config /etc/dovecot
COPY container/run-dovecot /run-dovecot

EXPOSE 24 143 993 3659 4190
ENTRYPOINT ["/run-dovecot"]
