FROM docker.io/debian:bookworm-slim@sha256:f80c45482c8d147da87613cb6878a7238b8642bcc24fc11bad78c7bec726f340 AS builder
ARG VERSION=10.2.3 # renovate: datasource=github-releases depName=grafana/grafana extractVersion=^v(?<version>.*)$

WORKDIR /src

ADD https://dl.grafana.com/oss/release/grafana-${VERSION}.linux-amd64.tar.gz /src.tar.gz
RUN tar --no-same-owner --strip-components 1 -xvzf /src.tar.gz && \
    install -D --mode 0755 /src/bin/grafana /build/usr/bin/grafana && \
    mkdir -p /build/usr/share/grafana && cp -R /src/public /build/usr/share/grafana/public

FROM docker.io/debian:bookworm-slim@sha256:f80c45482c8d147da87613cb6878a7238b8642bcc24fc11bad78c7bec726f340
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends curl
RUN adduser --system --group --uid 10000 --home /var/lib/grafana grafana

COPY --from=builder /build /
COPY container/config /etc/grafana

USER grafana
ENTRYPOINT ["/usr/bin/grafana", "server", "--config", "/etc/grafana/grafana.ini", "--homepath", "/usr/share/grafana", "web"]
