FROM docker.io/debian:bookworm-slim@sha256:2ccc7e39b0a6f504d252f807da1fc4b5bcd838e83e4dec3e2f57b2a4a64e7214 AS builder
ARG VERSION=11.1.4 # renovate: datasource=github-releases depName=grafana/grafana extractVersion=^v(?<version>.*)$

WORKDIR /src

ADD https://dl.grafana.com/oss/release/grafana-${VERSION}.linux-amd64.tar.gz /src.tar.gz
RUN tar --no-same-owner --strip-components 1 -xvzf /src.tar.gz && \
    install -D --mode 0755 /src/bin/grafana /build/usr/bin/grafana && rm -Rf /src/bin && \
    mkdir -p /build/usr/share && cp -R /src /build/usr/share/grafana

FROM docker.io/debian:bookworm-slim@sha256:2ccc7e39b0a6f504d252f807da1fc4b5bcd838e83e4dec3e2f57b2a4a64e7214
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends curl
RUN adduser --system --group --uid 10000 --home /var/lib/grafana grafana

COPY --from=builder /build /
COPY container/config /etc/grafana

USER grafana
ENTRYPOINT ["/usr/bin/grafana", "server", "--config", "/etc/grafana/grafana.ini", "--homepath", "/usr/share/grafana", "web"]
