FROM docker.io/debian:bookworm-slim@sha256:7c7b2c966bc9ee8cedfeef67e0e279108992c77681fa595db4a9d65c06ccc587 AS builder
ARG VERSION=5.5.2 # renovate: datasource=github-releases depName=go-acme/lego extractVersion=^v(?<version>.*)$

WORKDIR /src

ADD https://github.com/go-acme/lego/releases/download/v${VERSION}/lego_v${VERSION}_linux_amd64.tar.gz /src.tar.gz
RUN tar --no-same-owner -xvzf /src.tar.gz && \
    install -D --mode 0755 /src/lego /build/usr/bin/lego

FROM docker.io/debian:bookworm-slim@sha256:7c7b2c966bc9ee8cedfeef67e0e279108992c77681fa595db4a9d65c06ccc587
RUN apt-get update -y && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends ca-certificates gettext gosu

RUN adduser --system --group --uid 10000 --home /var/lib/letsencrypt letsencrypt

COPY --from=builder /build /
COPY container/run-lego /run-lego
COPY container/deploy-hook /deploy-hook

ENTRYPOINT ["/run-lego"]
