FROM docker.io/debian:bookworm-slim@sha256:56ff6d36d4eb3db13a741b342ec466f121480b5edded42e4b7ee850ce7a418ee AS builder
ARG VERSION=4.31.0 # renovate: datasource=github-releases depName=go-acme/lego extractVersion=^v(?<version>.*)$

WORKDIR /src

ADD https://github.com/go-acme/lego/releases/download/v${VERSION}/lego_v${VERSION}_linux_amd64.tar.gz /src.tar.gz
RUN tar --no-same-owner -xvzf /src.tar.gz && \
    install -D --mode 0755 /src/lego /build/usr/bin/lego

FROM docker.io/debian:bookworm-slim@sha256:56ff6d36d4eb3db13a741b342ec466f121480b5edded42e4b7ee850ce7a418ee
RUN apt-get update -y && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends ca-certificates gettext gosu

RUN adduser --system --group --uid 10000 --home /var/lib/letsencrypt letsencrypt

COPY --from=builder /build /
COPY container/run-lego /run-lego
COPY container/run-hook /run-hook

ENTRYPOINT ["/run-lego"]
