#!/bin/sh

set -eu

# Common-use variables.
DATA_DIR=/var/lib/rss2email
CONF_DIR=/etc/rss2email/feeds.d

# Parse invividual feed configuration directories.
process() {
    printf "Processing feeds for %s...\n" "$2"
    install -D --owner rss2email --group rss2email --target-directory "$DATA_DIR/feeds/$2/.rss2email" "$1"/*
    chown rss2email:rss2email "$DATA_DIR/feeds/$2/.rss2email"
    gosu rss2email sh -c "HOME=$DATA_DIR/feeds/$2 rss2email cron -verbose $2"
}

for feed in "$CONF_DIR"/*/feeds.txt; do
    process "$(dirname "$feed")" "$(basename "$(dirname "$feed")")"
done
