#!/bin/sh

set -eu

# Common-use variables.
DATA_DIR=/var/lib/rss2email
CONF_DIR=/etc/rss2email/feeds.d

# Parse invividual feed configuration directories.
process() {
    echo "Processing feeds for $1..."

    RSS2EMAIL_TO="$1" envsubst < "/etc/rss2email/rss2email.conf.template" > "/etc/rss2email/$1.conf"
    cat "$CONF_DIR/$1.conf" >> "/etc/rss2email/$1.conf"

    gosu rss2email r2e --config "/etc/rss2email/$1.conf" --data "$DATA_DIR/$1.json" run
}

for feed in "$CONF_DIR"/*.conf; do
    process "$(basename "$feed" .conf)"
done
