#!/bin/sh
set -eu

# Correct permissions where needed.
chown -R radicale:radicale /var/lib/radicale

# Prepare configuration files for environment variable substitution.
ENV_NAMES="$(env | awk -F '=' '{printf "$%s ", $1}')"
for file in /etc/radicale/*.template; do
	envsubst "$ENV_NAMES" < "$file" > "${file%.template}"
done

exec gosu radicale /venv/bin/radicale --config /etc/radicale/radicale.conf "$@"
