#!/bin/sh

# Prepare configuration files for environment variable substitution.
ENV_NAMES="`env | awk -F '=' '{printf "$%s ", $1}'`"
for file in /etc/radicale/*.template; do
	envsubst "${ENV_NAMES}" < "$file" > "`echo $file | awk -F '.template$' '{print $1}'`"
done

/venv/bin/radicale --config /etc/radicale/radicale.conf "$@"
