FROM docker.io/debian:bookworm-slim@sha256:e46f120bae54335b5d53129123104b3d9d47321fbb2a5573db0617bbac028cd5 AS builder
ARG VERSION=1.7.1 # renovate: datasource=github-releases depName=go-shiori/shiori extractVersion=^v(?<version>.*)$

WORKDIR /src

ADD https://github.com/go-shiori/shiori/releases/download/v${VERSION}/shiori_Linux_x86_64.tar.gz /src.tar.gz
RUN tar --no-same-owner -xvzf /src.tar.gz && \
    install -D --mode 0755 /src/shiori /build/usr/bin/shiori

FROM docker.io/debian:bookworm-slim@sha256:e46f120bae54335b5d53129123104b3d9d47321fbb2a5573db0617bbac028cd5
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    ca-certificates gettext gosu

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    curl

RUN adduser --system --group --uid 10000 --home /var/lib/shiori shiori

COPY --from=builder /build /

USER shiori
ENTRYPOINT ["/usr/bin/shiori", "serve"]
